/**
 * The trusted-source registry.
 *
 * `kind: 'policy'` items are official government output (GOV.UK department
 * feeds, regulators). `kind: 'news'` items are journalism and sector press.
 * Everything here is a public RSS/Atom feed — no API key required — which is
 * why the app has real content the moment you clone it.
 *
 * `hints` seeds the classifier: the AI can override them, the deterministic
 * fallback leans on them.
 */
export const FEEDS = [
  // --- Official: GOV.UK departments ---------------------------------------
  {
    id: 'govuk-dwp',
    name: 'DWP',
    publisher: 'GOV.UK — Department for Work and Pensions',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/department-for-work-pensions.atom',
    hints: ['benefits-welfare', 'jobs-market'],
    audience: ['jobseekers', 'employees'],
  },
  {
    id: 'govuk-dfe',
    name: 'Dept for Education',
    publisher: 'GOV.UK — Department for Education',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/department-for-education.atom',
    hints: ['education', 'skills-training', 'apprenticeships'],
    audience: ['students', 'apprentices', 'parents'],
  },
  {
    id: 'govuk-dbt',
    name: 'Dept for Business & Trade',
    publisher: 'GOV.UK — Department for Business and Trade',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/department-for-business-and-trade.atom',
    hints: ['business', 'pay-rights', 'economy'],
    audience: ['employees', 'employers'],
  },
  {
    id: 'govuk-treasury',
    name: 'HM Treasury',
    publisher: 'GOV.UK — HM Treasury',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/hm-treasury.atom',
    hints: ['economy'],
    audience: ['employees', 'employers'],
  },
  {
    id: 'govuk-home-office',
    name: 'Home Office',
    publisher: 'GOV.UK — Home Office',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/home-office.atom',
    hints: ['immigration-visas'],
    audience: ['migrants', 'employers'],
  },
  {
    id: 'govuk-hmrc',
    name: 'HMRC',
    publisher: 'GOV.UK — HM Revenue & Customs',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/hm-revenue-customs.atom',
    hints: ['pay-rights', 'economy'],
    audience: ['employees', 'employers'],
  },
  {
    id: 'govuk-dsit',
    name: 'DSIT',
    publisher: 'GOV.UK — Science, Innovation and Technology',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/department-for-science-innovation-and-technology.atom',
    hints: ['technology', 'skills-training'],
    audience: ['employees', 'career-changers'],
  },
  {
    id: 'govuk-dhsc',
    name: 'Dept of Health & Social Care',
    publisher: 'GOV.UK — Department of Health and Social Care',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/department-of-health-and-social-care.atom',
    hints: ['public-sector'],
    audience: ['employees', 'jobseekers'],
  },
  {
    id: 'govuk-skills-england',
    name: 'Skills England',
    publisher: 'GOV.UK — Skills England',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/skills-england.atom',
    hints: ['skills-training', 'apprenticeships', 'jobs-market'],
    audience: ['apprentices', 'career-changers', 'jobseekers'],
  },
  {
    id: 'govuk-ukvi',
    name: 'UK Visas & Immigration',
    publisher: 'GOV.UK — UK Visas and Immigration',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/uk-visas-and-immigration.atom',
    hints: ['immigration-visas'],
    audience: ['migrants', 'employers'],
  },
  {
    id: 'govuk-ofs',
    name: 'Office for Students',
    publisher: 'GOV.UK — Office for Students',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/office-for-students.atom',
    hints: ['education', 'graduates'],
    audience: ['students', 'graduates'],
  },
  {
    id: 'govuk-esfa',
    name: 'Education & Skills Funding',
    publisher: 'GOV.UK — Education and Skills Funding Agency',
    kind: 'policy',
    url: 'https://www.gov.uk/government/organisations/education-and-skills-funding-agency.atom',
    hints: ['apprenticeships', 'skills-training', 'education'],
    audience: ['apprentices', 'students'],
  },

  // --- Official: statistics & regulators -----------------------------------
  {
    id: 'ons-releases',
    name: 'ONS',
    publisher: 'Office for National Statistics',
    kind: 'policy',
    url: 'https://www.ons.gov.uk/releasecalendar?rss',
    hints: ['economy', 'jobs-market'],
    audience: ['employees', 'employers'],
  },
  {
    id: 'boe-news',
    name: 'Bank of England',
    publisher: 'Bank of England',
    kind: 'policy',
    url: 'https://www.bankofengland.co.uk/rss/news',
    hints: ['economy'],
    audience: ['employees'],
  },

  // --- Journalism -----------------------------------------------------------
  {
    id: 'bbc-business',
    name: 'BBC Business',
    publisher: 'BBC News',
    kind: 'news',
    url: 'https://feeds.bbci.co.uk/news/business/rss.xml',
    hints: ['economy', 'business', 'jobs-market'],
    audience: ['employees', 'jobseekers'],
  },
  {
    id: 'bbc-education',
    name: 'BBC Education',
    publisher: 'BBC News',
    kind: 'news',
    url: 'https://feeds.bbci.co.uk/news/education/rss.xml',
    hints: ['education', 'skills-training'],
    audience: ['students', 'parents'],
  },
  {
    id: 'bbc-technology',
    name: 'BBC Technology',
    publisher: 'BBC News',
    kind: 'news',
    url: 'https://feeds.bbci.co.uk/news/technology/rss.xml',
    hints: ['technology'],
    audience: ['employees', 'career-changers'],
  },
  {
    id: 'guardian-careers',
    name: 'Guardian Careers',
    publisher: 'The Guardian',
    kind: 'news',
    url: 'https://www.theguardian.com/careers/rss',
    hints: ['jobs-market', 'skills-training'],
    audience: ['jobseekers', 'career-changers'],
  },
  {
    id: 'guardian-work',
    name: 'Guardian Work & Careers',
    publisher: 'The Guardian',
    kind: 'news',
    url: 'https://www.theguardian.com/money/work-and-careers/rss',
    hints: ['pay-rights', 'jobs-market'],
    audience: ['employees'],
  },
  {
    id: 'guardian-education',
    name: 'Guardian Education',
    publisher: 'The Guardian',
    kind: 'news',
    url: 'https://www.theguardian.com/education/rss',
    hints: ['education'],
    audience: ['students', 'parents'],
  },
  {
    id: 'sky-business',
    name: 'Sky News Business',
    publisher: 'Sky News',
    kind: 'news',
    url: 'https://feeds.skynews.com/feeds/rss/business.xml',
    hints: ['economy', 'business'],
    audience: ['employees'],
  },
  {
    id: 'personnel-today',
    name: 'Personnel Today',
    publisher: 'Personnel Today',
    kind: 'news',
    url: 'https://www.personneltoday.com/feed/',
    hints: ['pay-rights', 'jobs-market'],
    audience: ['employees', 'employers'],
  },
  {
    id: 'guardian-students',
    name: 'Guardian Students',
    publisher: 'The Guardian',
    kind: 'news',
    url: 'https://www.theguardian.com/education/students/rss',
    hints: ['education', 'graduates'],
    audience: ['students', 'graduates'],
  },
  {
    id: 'guardian-economics',
    name: 'Guardian Economics',
    publisher: 'The Guardian',
    kind: 'news',
    url: 'https://www.theguardian.com/business/economics/rss',
    hints: ['economy', 'jobs-market'],
    audience: ['employees', 'employers'],
  },
  {
    id: 'sky-politics',
    name: 'Sky News Politics',
    publisher: 'Sky News',
    kind: 'news',
    url: 'https://feeds.skynews.com/feeds/rss/politics.xml',
    hints: ['economy', 'benefits-welfare'],
    audience: ['employees', 'jobseekers'],
  },
  {
    id: 'independent-business',
    name: 'The Independent — Business',
    publisher: 'The Independent',
    kind: 'news',
    url: 'https://www.independent.co.uk/news/business/rss',
    hints: ['business', 'economy'],
    audience: ['employees', 'employers'],
  },
];

export const feedById = (id) => FEEDS.find((feed) => feed.id === id) ?? null;
